baseURL = "https://ferreira.page/"
title = "Ferreira's Adoption Journey"
theme = "hugo-scroll"

# this is a "one page" website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS"]

languageCode = "en-us"
defaultContentLanguage = "en"

canonifyURLs = true
enableRobotsTXT = true

publishDir = "docs"

[params]
    title = "Ferreira's Adoption Journey"
    copyright = "Copyright © 2022 Ferreira • All Rights Reserved"
    description = "Ferreira's Adoption Journey"
    favicon = "images/flag-colombia.png"
    images = ["images/cover-image.jpg"]

    hidedesignbyline = true

    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
