baseURL = "https://ferreira.page/"
title = "Ferreira's Adoption Journey"
theme = "hugo-scroll"

disableKinds = ["section", "taxonomy", "term", "RSS"]

languageCode = "en-us"
defaultContentLanguage = "en"

canonifyURLs = true
enableRobotsTXT = true

publishDir = "docs"

[params]
    # This title is used as the site_name on the Hugo's internal opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Ferreira's Adoption Journey"

    # A "copyright"-line to be added at the bottom of the page.
    copyright = "Copyright © 2022 Ferreira • All Rights Reserved"

    # This is used in the meta data of your generated html.
    description = "Ferreira's Adoption Journey"
    
    # Path to a (at least 32px x 32px) png-file.
    favicon = "images/flag-colombia.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/cover-image.jpg"]

    hidedesignbyline = true

    [params.meta]
        keywords = "ferreira, adoption, colombia, christian, lifelife, Jesus, God, bible"
